atiknakit_failed_uploads = "_atiknakit_failed_uploads.json"
atiknakit_failed_locations = "_atiknakit_failed_locations.json"
uploaded_files = "_uploaded_files.json"
garbage_location_list_file = "../_garbage_locations.json"
device_config_file = "../device_configs.json"
