url_location_upload = "https://api2.atiknakit.com/uploadGarbageDeviceLocations/"
url_image_info_upload = "https://api2.atiknakit.com/uploadGarbageDeviceImage/"
url_connection = "https://cdn.atiknakit.com/"
url_garbage_locations = "https://api2.atiknakit.com/garbagedevice/"
url_cdn_upload = "https://cdn.atiknakit.com/upload?"
