URL_LOCATION_UPLOAD = "https://api2.atiknakit.com/uploadGarbageDeviceLocations/"
URL_IMAGE_INFO_UPLOAD = "https://api2.atiknakit.com/uploadGarbageDeviceImage/"
URL_CONNECTION = "https://cdn.atiknakit.com/"
URL_GARBAGE_LOCATIONS = "https://api2.atiknakit.com/garbagedevice/"
URL_CDN_UPLOAD = "https://cdn.atiknakit.com/upload?"
URL_ATIKNAKIT_SERVER = "93.113.96.30"
URL_STREAM = "rtsp://93.113.96.30:8554/"
ATKNAKIT_SOCKET_SERVER = {"ip": "93.113.96.30", "port": 5003}
RPI_API_URL = "http://93.113.96.30:8081/"
